# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd4948aa16fa430cddbd6827dde1d5a4e084f7d8dd600607e76f2ee5dd76c5723401424db7e01302cc48dac2f870e396529bde163be024af743a1f053623cfa

test:
  secret_key_base: c8c715d9338ec273c05a9222cd380822eb1d9b3dbb11af628a6d058bcd107f407286caff01fe1384e50428f838bb82bbd8b258eaab6413b87623778f38b269fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
